### ISSUE TITLE
Inline Commenting and Moderation

### ISSUE THREAD

**Issue by mrcoolbp** [SoylentNews/slashcode#154]
As a fix for expanding/collapsing comments is in the works on the dev server, the next big usability feature for commenting would be to allow commenting and moderating within the same page (eliminating the need for multiple page loads). Currently, either commenting or moderating means losing one's place within a large discussion. 

(Posted on behalf of a user.)

**Comment by mrcoolbp** [comment]
Posted on behalf of a user:

"Currently, when I press the [Moderate] button the page refreshes and 'jumps' back to the top where it shows me a confirmation about the action done.

This looks more or less like this :

```
+1 (Insightful) Oh God, Worstall! (7497-184423, 3 points left)
```

Even though it's nice to have this confirmation, it also means I have to manually scroll down again to find the comment I moderated and continue reading. This is rather annoying and discourages me (and probably others too) to take part in the moderation system.
Would it be possible to add a 'jump back to comment' button/link next to or embedded into the 'summary line' ?

Since the numbers (e.g. 184423) already seem to refer to the comment ID it shouldn't be to hard to convert them into a link that jumps down, right?
It probably can be done in GreaseMonkey, but IMHO should be available right of the bat."

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#114
