### ISSUE TITLE
Search functionality broken

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/slashcode#17]
Under Topics --> Navigation, the word “Topics” refers to Search, but the search functionality seems fundamentally broken. Additionally: “Topics” is not an intuitive word for “Search”. Under “Topics”, there are several links for searching different sections of the. All of this is confusing. Edit: Just found Navigation --> Older Stuff leads to another search as well. Navigation --> Past Polls ==> More Polls is also another search.

**Comment by NCommander** [comment]
Replaced with sphinx based search in rehash. Will be fixed in next major release.
