### ISSUE TITLE
Submission Preview Disappeared

### ISSUE THREAD

**Issue by lhsi** [SoylentNews/slashcode#174]
I was editing and previewing a submission when I got an empty submission page (just the form, empty with no preview). I could click the back button to get the text back so just hit submit which did seem to work. 

As  a side effect, I missed adding in the URL so had to re-submit the story - how long is the delay before you are allowed to submit again as I couldn't do it straight away.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#116
