### ISSUE TITLE
When returning to a story, highlight any new comments

### ISSUE THREAD

**Issue by Open4D** [SoylentNews/slashcode#179]
Feature request:

Allow users to opt in to have their story viewing tracked - so that you know which comments they have already (potentially) read.  If they visit the same page of comments again, highlight any new comments - perhaps in a different colour.  (Or perhaps the new comments should be 'normal' and the old comments should be in a different colour.)

For performance reasons, you might want to only remember the 50 most recently visited stories, per user, or something.

You might want to implement this not just for comments that are *new*, but also for comments that haven't been loaded yet by that user for any other reason - e.g. if the user has just lowered his/her threshold, or if a comment has been modded up to reach the user's threshold.

(Credit [to kaszz](http://soylentnews.org/comments.pl?sid=1790&cid=42357).)

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#118
