### ISSUE TITLE
"No discussion or comments found for this request"

### ISSUE THREAD

**Issue by Open4D** [SoylentNews/slashcode#180]
Sometimes I type out a comment, click "Preview", and get a page with the following message:
*No discussion or comments found for this request. To create your own discussion, please use journals.*

Luckily I can just click my web browser's back button, and it takes me back to the comment entry page, and it remembers the text that I had typed out.  I then click "Preview" again and it works as normal.

I've probably encountered this less than 10 times, and probably only in the last few weeks.  Most recent was at 2014-05-13T09:45Z.  I saved the HTML, in case it's of any use.

**Comment by Open4D** [comment]
I don't remember getting this in a long time.  What about you @tathra ?  Shall I close this?

**Comment by TheMightyBuzzard** [comment]
Nah, I've gotten it recently. Seems to only happen if you leave tabs open for days on end or through several restarts of the server though.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#119
