### ISSUE TITLE
Logged out and back in with no action other than reload

### ISSUE THREAD

**Issue by agilbertson1977** [SoylentNews/slashcode#216]
18:27 < AndyTheAbsurd> so I reloaded the website not long before I left for work this morning, and it showed me as not being logged in
18:27 < AndyTheAbsurd> but I reloaded again a couple of minutes ago (after I got back from work) and now I'm logged in again
18:27 < AndyTheAbsurd> so...I guess there's something funky going on with the login code?
18:28 < TheMightyBuzzard> very possible
18:28 <@paulej72> more likely the login cookie madness
18:28 < AndyTheAbsurd> probably a known bug, then?  Do you want any info from me to help locate/debug the issue?
18:30 <@paulej72> AndyTheAbsurd: not an issue that sepcifically heard before. you can file an issue on github if you want.

So I filed this bug.  No idea what's going on; I wasn't doing anything strange, I didn't take any unusual browser actions or restart the browser or restart my computer...just...not logged in the morning, figured my previous login had expired and I would log in again when I got back, got back 10 hours later, reloaded the page to read the newest stories and BOOM I was logged in again.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#121
