### ISSUE TITLE
Images in story submission

### ISSUE THREAD

**Issue by lhsi** [SoylentNews/slashcode#231]
[Feature request]

What are the thoughts of allowing images in a story submission? Not as something to include all the time, but I think some would be enhanced by it. 

I have submitted a couple of stories and thought it would have benefited from showing one of the graphs used, or if something is new or unusual (for example, I recently submitted a story about a new species of dinosaur but had no way to include the image of what it might have looked like). 

Maybe if an image is included, it is after the "Read More" break to stop it appearing on the main page.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#124
