### ISSUE TITLE
Journal user box too low down by default

### ISSUE THREAD

**Issue by Jaruzel** [SoylentNews/slashcode#241]
Since the relocation of the Site News user box to the right hand side, and the regular appearance of the Poll user box and moderation user box, the Journals user box is now too far down the page for anyone to really see it, as such people are commenting a lot less on Journals (and one assumes less people are reading them also)

I think the journals are a good 'community' feature and should be promoted as such.
Therefore can we look at reshuffling the default layout of the user boxes?

(I know user box  management is available in the preferences, but I would think most people don't bother to do that)

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#126
