### ISSUE TITLE
Submit Poll lack of clarity

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/slashcode#26]
Navigation --> Past Polls ==> Submit Poll : Goes to same page as Navigation --> Submit Story; In other words, submitted a poll makes it looks like you are submitting a story. 

Message
Date: 2014-02-16 12:01
Sender: Michael Casadevall

There's no submit poll UI. Probably just a good idea to remove that link.

**Comment by bart9h** [comment]
Maybe nobody submits because there's no way to do that.

I, for one, would like to submit polls, and already searched in vain for a form to do that.
