### ISSUE TITLE
Poll page title incorrect

### ISSUE THREAD

**Issue by cc158981bce50e050022f4ab8f113ece** [SoylentNews/slashcode#261]
Some polls have the wrong &lt;title&gt;. At first I thought it was the most recent poll's title or the last visited poll's title but it appears to be random. Some kind of caching problem?

To recreate visit http://dev.soylentnews.org/pollBooth.pl, click on a poll. The page &lt;title&gt;s seem to be random. If you click [Results] you can also get an incorrect title.

Refreshing (Ctrl-F5) the page can lead to a different title. Visiting other polls can show the same title or a different title.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#128
