### ISSUE TITLE
Check all tasks to see if any are unnecessary (i.e based on removed code)

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#268]
repeated errors accesslog_artcom.pl odd exit (status 38, signal 0)

NOTE: I have editor privs on the main site.
In my preferences, I set "Daily Site Stats" to "E-mail".
According to paulej72: "the daily site stats sends slashd errors as well" 
Approximately every 5 minutes (but occasionally twice a minute or once every 10 minutes) I received an e-mail containing:

SoylentNews Slashd Error Alert!
SLASHD line 165 produced the following error:
accesslog_artcom.pl odd exit (status 38, signal 0)

paulej72 also informed me "it is running and failing. it is set to run every 5 minutes."

Makes it hard to get site stats when there are about 150 of these messages each day.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#129
