### ISSUE TITLE
Apache 2 upgrade.

### ISSUE THREAD

**Issue by paulej72** [SoylentNews/slashcode#277]
Get our code onto Apache 2 branch, wether 2.2 or 2.4 is more dependent on mod_perl support for each.

Here are some references http://perl.apache.org/docs/2.0/user/porting/compat.html, http://perl.apache.org/docs/2.0/user/porting/porting.html. 

I was reading trough these documents and found a issue with our code, but damn if I can find it now.

The goal of this migration is to allow us to use a modern version of Apache that is still being maintained.

**Comment by NCommander** [comment]
I think we can close this one now :)
