### ISSUE TITLE
Nagger doesn't update after submission

### ISSUE THREAD

**Issue by lhsi** [SoylentNews/slashcode#281]
The nagger doesn't update after a submission, you need to go to a new page to see the new total. 

Step to reproduce: Submit an article submission when there are less than 20 stories in the queue (so the nagger line appears at the top of the page). You are taken to the "Submission received" page (the one that confirms that the submission was received). 

Expected: The "Number of stories in the queue" has gone up by one with a new story
Actual: The number remains unchanged. Going to a new page has a new number

Workaround: Go to a new page to see the updated number.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#131
