### ISSUE TITLE
DDNS for subscribers

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/slashcode#294]
Was looking at dynamic dns for some reason the other night and it struck me that this was one thing we could offer subscribers without too much hassle. Very low traffic, very low disk space, very low processor time, ideally zero maintainance, moderate value. Thoughts?

They may need to be hosted under a subdomain of course to prevent confusion with official servers.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#133
