### ISSUE TITLE
Contributors scoreboard

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/slashcode#306]
It'd be nice for users to be able to see where they stand in relation to other users as far as accepted submissions go. A scoreboard. Charts for overall, monthly, yearly. Well we can probably skip yearly for now but you get the point. 

The same might not be a bad idea for commenters. Even broken down by comments' moderation. Who has the most +5 comments? Who has the most troll comments? You get the point.

Also, I'm thinking badges like the subscriber badge might not be a bad idea for the most active submitters. Maybe earned after N submissions, maybe dynamically held by the top 10/10%/whatever submitters.

**Comment by mrcoolbp** [comment]
I would like to see the HallOfFame page linked somewhere, not sure where would be best. I would also like to see the following on HoF page:

Top Acceptance Rate (% subs accepted)
Expand Top-Submitters to 20 users
"Authors" renamed to "Editors"
Most Comments
Most Up-modded Comments
Most Moderations Performed

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#135
