### ISSUE TITLE
Submission Categories Rework

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/slashcode#319]
We run enough political stories that we should probably include a Politics category at the very least. It's been suggested on IRC that categories could even use a more thorough rework. This ideally needs a half hour to an hour of suggesting and arguing at a staff meeting to hammer out.

**Comment by mrcoolbp** [comment]
I recommend "Breaking News" as a topic

**Comment by mrcoolbp** [comment]
We'll need to get some new icons as P.J. mentioned, so once we have a list of topics we like, let me know and I'll see if our icon guy wants to do some more work.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#138
