### ISSUE TITLE
Non-Meta-Moderation Refresh

### ISSUE THREAD

**Issue by TheMightyBuzzard** [SoylentNews/slashcode#320]
We're more or less running stock slashdot categories for moderation. I'd like us, prior to work going into m2 (#278), to sit down and have a discussion of what moderations need the axe, which should stay, and what new ones we want to include. This doesn't need to be done via dev fiat though, it should be argued at in a staff meeting and either decided by the CEO or delegated to the User Experience team lead.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#139
