### ISSUE TITLE
'_pk_ref.1.2d83'  cookie contains http_referer URL. Possible breach of privacy.

### ISSUE THREAD

**Issue by Jaruzel** [SoylentNews/slashcode#327]
Athough it is accepted that HHTP web logs can catch the referring url of a page request, it also seems that Slashcode is grabbing it and at the very least sending it back to the user as a cookie (_pk_ref.1.2d83) - Is this required, and what else is slashcode doing with it?  

From a privacy point of view, it could expose users browsing habits.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#141
