### ISSUE TITLE
ModPoints available after stated expiration date/time

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#330]
Mod Point expiration date/time was in the past

- Reloaded the site home page: http://soylentnews.org
- Saw notice that I had mod points:
   Moderation
   You have 10 Moderator Points! Use 'em or lose 'em!
   Your points expire at 2014-09-11 11:09.
   etc.
- The current time on my system was approximately: 11:20 AM EDT. (Eastern Daylight Time)
- I opened a story and moderated 3 comments,
- I refreshed the main site page.
- Saw the message updated to be:
   You have 7 Moderator Points! Use 'em or lose 'em!
   Your points expire at 2014-09-11 11:09.
   etc.
- My preferences are set to display as EDT. 
- Cannot tell which it is, but it may be a problem with converting UTC to eastern *daylight* time, or, an error in computing a date/time stamp in a window around 12noon vs 12midnight.
- Since I should not be able to perform moderation after my modpoints have expired, I expect it is a problem in computing/displaying the date/time for mod points expiration.

**Comment by NCommander** [comment]
Closing this one out, given mod rewrite. If its still an issue, reopen.
