### ISSUE TITLE
HTTPS practices

### ISSUE THREAD

**Issue by frojack** [SoylentNews/slashcode#364]
Item one:
If one points a web browser at https://www.soylentnews.org (yes, with the www), you will most often not be logged in upon arrival.  Upon logging in, you will be taken to an insecure connection.

If you visit https://soylentnews.org  (without www) it behaves properly and will retain a secure connection after log in.

If the www prefix is to be supported at all, it should probably be supported properly, and remain on an https connection.

Item two:
If someone goes to their password setting page the connection should switch to secure (https)
One could argue that login should always be done securely.

**Comment by NCommander** [comment]
The site is going HTTPS by default with the next upgrade, this should be fully resolved withat. Closing bug.
