### ISSUE TITLE
Enhancement(s) for "recently" accepted submissions

### ISSUE THREAD

**Issue by Open4D** [SoylentNews/slashcode#377]
At the bottom of each user page is a "Recently Accepted Submissions" section.  It is not clear how the list of accepted submissions is being limited based on how recent they were.

Example with 386 submissions: http://soylentnews.org/~lhsi/

Perhaps the text should say "Showing **all** 386 submissions" or "Showing all submissions in the last 12 months" or something, to help reflect whatever the actual limits are?

(As a long term change - actual code rather than just wording - perhaps it should be limited to the most recent 50 submissions, with only subscribers getting access to the older blocks of 50?)

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#146
