### ISSUE TITLE
Length of moderation points in mod instructions

### ISSUE THREAD

**Issue by Magic-Oddball** [SoylentNews/slashcode#378]
According to the Moderation Instructions, mod points only last 8 hours — yet at 8:30pm I noticed that I have mod points that won't expire until 2:11pm tomorrow ("2014-11-03 14:11").  Even my severely dyscalculic brain can tell that doesn't quite add up.  :-)

I'm guessing that either:
--the main page should have "UTC" appended after the time, or
-- it should state the user's local time, or
-- the instructions need to be updated to reflect how long we now get points

(I'm hoping that the instructions are merely outdated, since eight hours seems way too short to me!)

**Comment by paulej72** [comment]
now it it all messed up again as we updated the mod system and did not update the docs.  Silly us.

**Comment by paulej72** [comment]
Fixed in #413
