### ISSUE TITLE
"Black IcIcle" theme name miscapitalized

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#397]
Capitalization of the user-visible them name "Black IcIcle" is incorrect; should be "Black Icicle" (i.e. the second letter "i" should be lowercase.  In a sans-serif font, e.g. Arial, a capital "I" and a lowercase "l" look virtually identical... this capitalization makes it hard for me to read.

Please lowercase the second letter "I" in "Icicle".

Here is a view of the source HTML where this occurs:

[select id="skin" name="skin"]
	[option value=""]Site Default[/option]
	[option value="bada55"]BadA55[/option]
	[option value="chillax"]Chillax[/option]
	[option value="icicle"]Black IcIcle[/option]
	[option value="night"]Night Mode[/option]
	[option value="pwnies" selected]OMG PWNIES[/option]
	[option value="soylentnews"]SoylentNews[/option]
	[option value="vt100"]VT100[/option]
[/select]

**Comment by TheMightyBuzzard** [comment]
This was actually intentional.
