### ISSUE TITLE
newly-supported abbr element stripped spaces from title text in comments

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#398]
It appears that the newly-supported abbr element strips spaces from its title text.
Given:

[abbr title="North Atlantic Treaty Organization]NATO[/abbr]

When I hovered my mouse over "NATO" in preview I saw: "NorthAtlanticTreatyOrganization" — spaces were stripped from between the words.

See: https://dev.soylentnews.org/comments.pl?sid=1147&cid=28228

**Comment by TheMightyBuzzard** [comment]
Fixed in the upcoming pull request.
