### ISSUE TITLE
ABBR element stripped from submitted story text

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#399]
Tested on dev.soylentnews.org
Submitted a new story; see: https://dev.soylentnews.org/submit.pl?op=viewsub&subid=1175
(Here I am using square brackets "[" "]" where less-than and greater-than would otherwise be present.)
Story *text* contained: "[abbr title="File Transfer Protocol">FTP[/abbr]"
Reviewed story submission using: https://dev.soylentnews.org/submit.pl?op=list
Saw the entire abbr phrase was in the submission.
Clicked on "Preview" button.
Saw entire ABBR phrase was removed.

**Comment by TheMightyBuzzard** [comment]
Dev was not up to date. Closing.
