### ISSUE TITLE
API quirk

### ISSUE THREAD

**Issue by crutchy-** [SoylentNews/slashcode#400]
passing a uid of 1e6 or 1xxx returns AC. demo: https://dev.soylentnews.org/api.pl?m=user&op=get_nick&uid=1e6

submitted by exec on behalf of crutchy from #Soylent @ irc.sylnt.us

**Comment by TheMightyBuzzard** [comment]
Found the cause. Here it's a bug, elsewhere it's a feature, so it can just stay a documented bug here.
