### ISSUE TITLE
Bug 230 regression(?)

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#401]
Cf bug 230.
Look at source to this page: http://dev.soylentnews.org/article.pl?sid=15/01/20/1426201
I still see a script referring to coremetrics being inserted:

&lt;script type="text/javascript"&gt;
// coremetrics
if( window.location.hostname.indexOf('slashdot.org') &gt;= 0 ) {
	cmSetProduction();
}
cmCreatePageviewTag && cmCreatePageviewTag('ARTICLE DETAIL', null, null, null,'New "user" tag tests -- Plain Old Text-_-') && (cmCreatePageviewTag = null);
&lt;/script&gt;

&lt;div class="prev-next"&gt;

**Comment by paulej72** [comment]
fixed will be in an upcoming pull request.
