### ISSUE TITLE
Daily Site Stats Email - Privacy Leak

### ISSUE THREAD

**Issue by juggs** [SoylentNews/slashcode#405]
The daily site stats email reveals new user email addresses.

Email subject: [SoylentNews] SoylentNews Stats for $date

Has a section titled "3 random users created yesterday:" which contains 3 usernames, their ID and their registered email address.

This section needs to be dropped in favour of a simple line that states "N new users created yesterday" - where N = number of new user accounts that day.

Email is insecure, we should not be transmitting users email addresses in this way.

**Comment by paulej72** [comment]
Temp fix by removing the emails from the template.  Need to looking into replacing it with actual numbers.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#153
