### ISSUE TITLE
an internal link in the story has "tid" in the end, not work

### ISSUE THREAD

**Issue by cnst** [SoylentNews/slashcode#409]
http://soylentnews.org/article.pl?sid=15/02/01/1238230

The "OpenSSL-free" link has a "tid" string in the end, resulting in not work, 404 Not Found.

I'm not sure how it got added, but it wasn't present in my submission.  The link doesn't work with the extra string.  Please remove and investigate how it was introduced.

**Comment by TheMightyBuzzard** [comment]
fixed
