### ISSUE TITLE
Login Redirection from tor

### ISSUE THREAD

**Issue by mechanicjay** [SoylentNews/slashcode#412]
When logging in via some alternate url, such as the .onion site:  http://7rmath4ro2of2a42.onion/

After login is complete you are redirected back to https://soylentnews.org/  regardless of where you were when you logged in.

Once on the soylentnews.org site, you're not logged in because the cookie is for the .onion domain.  Once you revisit the .onion url, you are logged in and things seems to work as they should.

The form action and the returnto values are set properly, I'm guessing the final step in the login procedure is where this is falling down.

**Comment by paulej72** [comment]
fixed will be in an upcoming pull request.

**Comment by paulej72** [comment]
Not fixed.  Redirect is working, but it is using the default server name.  Need to look into this some more.

**Comment by NCommander** [comment]
Fixed, this was an issue with the Apache 2.4 migration on nitrogen. Fixed when I migrated it to boron.
