### ISSUE TITLE
Malformed links in sn.org/my/inbox ?

### ISSUE THREAD

**Issue by mrcoolbp** [SoylentNews/slashcode#431]
When someone else responds to my posts and it shows up in the inbox [soylentnews.org] link [soylentnews.org] at this site. The link to the other persons answer will intermittently be invalid. (don't recall if it was a malformed link or missing destination)
There is an answer however which I found by using the link to my own post [soylentnews.org].

{ Submitted on behalf of user kaszz (4211) ] [Comment #158409](https://soylentnews.org/comments.pl?sid=6530&cid=158407) }

**Comment by paulej72** [comment]
I think this may be related to current issue with prod going brain dead periodically.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#157
