### ISSUE TITLE
No Comments Displayed under some Circumstances

### ISSUE THREAD

**Issue by mrcoolbp** [SoylentNews/slashcode#434]
A link which *should* take me to comments within a story (it doesn't seem to matter whether it's a "read more" or "# replies" or even clicking on a link to comments in a message I've received about a
reply or moderation.  The page refreshes and the story comes up, but no comments are displayed.

A reload of the page generally does not fix it.  Going back to the main page or to the message that had the link, and clicking on the story works sometimes, but not always. 

Eventually, I can get to the comments.  Perhaps there's some sort of race condition or a database lock that keeps the comments from being displayed?

n.b., I'm running Firefox ESR 31.5.0.

Logged on behalf of user NotSanguine (285)

**Comment by NCommander** [comment]
What URLs are displayed in the address bar?

**Comment by paulej72** [comment]
Seems it was a varnish or memcache issue.  Was getting these types of errors:

[Mon Mar 16 19:58:53 2015] [error] /article.pl:Slash::Utility::Comments:/srv/soylentnews.org/local/lib/perl5/site_perl/5.10.1/x86_64-linux/Slash/Utility/Comments.pm:1191:ID 395, printCommComments;misc;default : undef error - Can't use string ("improvedthreaded") as a HASH ref while "strict refs" in use at /srv/soylentnews.org/local/lib/perl5/site_perl/5.10.1/Slash/Moderation.pm line 1422.\n ;; Which was called by:Apache::ROOTsoylentnews_2eorg::article_2epl:/srv/soylentnews.org/slashcode/site/soylent-mainpage/htdocs/article.pl:200

There is no connection to user.mode (imporovedthreaded) and the code at the line numbers listed.  A restart of apache and varnish and a memecache flush, seems to have fixed the issue and the errors were not seen.  

May have been related to taking a tarball of the fluorine as backup the night before this was first seen.
