### ISSUE TITLE
Server Error when preview comment having char < 0x1f, or char==0x7f

### ISSUE THREAD

**Issue by marty-b** [SoylentNews/slashcode#435]
Tried to submit a comment to: https://dev.soylentnews.org/article.pl?sid=15/03/29/1622202
1.)  Viewed story
2.)  Clicked on Reply button
3.)  Entered comment title: "0x7f - POT"
4.)  Selected "Plain Old Text" from the Drop-Down list
5.)  Clicked on 'Preview' button.
6.)  Got server error:
OK

The server encountered an internal error or misconfiguration and was unable to complete your request.

Please contact the server administrator, slash@dev.soylentnews.org and inform them of the time the error occurred, and anything you might have done that may have caused the error.

More information about this error may be available in the server error log.

7.) paulej72 provided this snippet from logs:

[Sun Mar 29 20:49:50 2015] [error] /comments.pl:ModPerl::ROOT::ModPerl::Registry::srv_soylentnews_2eorg_rehash_site_soylent_2dmainpage_htdocs_comments_2epl:/srv/soylentnews.org/rehash/site/soylent-mainpage/htdocs/comments.pl:506:cannot getSkin for empty skid='0' ;; Which was called by:ModPerl::ROOT::ModPerl::Registry::srv_soylentnews_2eorg_rehash_site_soylent_2dmainpage_htdocs_comments_2epl:/srv/soylentnews.org/rehash/site/soylent-mainpage/htdocs/comments.pl:329
[Sun Mar 29 20:51:00 2015] [error] Cannot decode string with wide characters at /srv/soylentnews.org/perl/lib/perl5/site_perl/5.20.1/x86_64-linux-thread-multi/Encode.pm line 241.\n

**Comment by marty-b** [comment]
Missing one step:
3.5) In the text entry area, insert a single character: 0x7f, i.e. ""

**Comment by NCommander** [comment]
Ugh. I'm guessing this is a problem with perl 5.20 vs. mod_perl 2. Paging
TMB.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#29
