### ISSUE TITLE
Feature for Leaving Notes to other Editors in "Stories List"

### ISSUE THREAD

**Issue by mrcoolbp** [SoylentNews/slashcode#437]
Currently there is no way to leave notes to other editors on a story that has been posted to the "Stories list". The "Submissions list" has a (lacking) feature allowing editors to leave quick notes (like "dupe", "weekend", etc.) to each other. I would like to see a similar feature for stories that have already been "posted" but it should be "better" than what we have in the submissions list.

takyon agrees and adds that the 'submissions note field' should be copied to the 'story note field' when someone saves the story to the "Stories list"

juggs adds that this feature would ideally be some kind of visible-only-to-editors scratchpad attached to each sub for notes with time-stamped [and "signed" so you know who left them] entries.

**Comment by paulej72** [comment]
Implemented in rehash
