### ISSUE TITLE
Notes to other editors on "Submissions List" needs expansion

### ISSUE THREAD

**Issue by mrcoolbp** [SoylentNews/slashcode#438]
Currently editors can leave notes to each other on the submissions list, this is useful for "dupe", "weekend", etc., but being able to leave more then 23 characters would be useful. (I'll note that more than 23 chars can be left in that box, but it's quite awkward to try to "scroll" through the note by selecting text and dragging)

I would love to see this feature expanded upon, especially with the feature showing WHO left each note!

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#158
