### ISSUE TITLE
Moderation FAQ incorrectly passing a const through to page content

### ISSUE THREAD

**Issue by juggs** [SoylentNews/slashcode#441]
How to reproduce:
1. Visit https://soylentnews.org/faq.pl?op=moderation#how
2. See text in page "Everyday each eligible moderator is given $constants.m1_pointsgrant_arbitrary mod points to play with."

Suggested fix:
1. Put the assigned value of $constants.m1_pointsgrant_arbitrary into the page text rather than the const name.

Simples! :D (Says the guy who doesn't have to fix it!)

~jiggles~

**Comment by paulej72** [comment]
fixed in #443
