### ISSUE TITLE
Quote Button

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/slashcode#446]
Feature request: a new button between "Reply to This" and "Parent" labelled "Quote".

Click on it, you get the same page as "Reply to This", except the postercomment textarea contains a blockquote with the contents of the parent post, followed by two line breaks.

**Comment by soytakyon** [comment]
Tweak to idea: eliminate all blockquotes within the quoted parent to eliminate clutter.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#161
