### ISSUE TITLE
Inbox "comment moderation" messages ignore karma bonus

### ISSUE THREAD

**Issue by soytakyon** [SoylentNews/slashcode#452]
"Comment moderation" messages in the inbox do not take into account the karma bonus when reporting a comment score.

For example, "Re:Comment, posted to Article, has been moderated Informative (+1). It is currently scored Informative (2)."

The actual score is Informative (3). If it is then moderated Overrated:

"Re:Comment, posted to Article, has been moderated Overrated (-1). It is currently scored Informative (1)."

The actual score is Informative (2).

If a comment is moderated beyond +5 including the karma bonus, then you can get a message stating the comment is scored Something (5).

**Comment by soytakyon** [comment]
Confirmed that the correct score is shown when there is no karma bonus.

**Comment by paulej72** [comment]
This issue was moved to SoylentNews/rehash#167
